services:
  users_service:
    build: ./users_service
    container_name: desafio5-users
    ports:
      - "6001:6001"
    networks:
      - desafio5-net

  orders_service:
    build: ./orders_service
    container_name: desafio5-orders
    ports:
      - "6002:6002"
    networks:
      - desafio5-net

  gateway:
    build: ./gateway
    container_name: desafio5-gateway
    depends_on:
      - users_service
      - orders_service
    environment:
      USERS_URL: http://users_service:6001/users
      ORDERS_URL: http://orders_service:6002/orders
    ports:
      - "7000:7000"
    networks:
      - desafio5-net

networks:
  desafio5-net:
    name: desafio5-net
